Title:              Theoretische Informatik 1
Subtitle:           Praktikumsaufgabe 3
Author:             Lucas Jenss und Tommy Redel in Gruppe 1
ShortAuthor:        Lucas Jenss und Tommy Redel
UseHelvetica:       yes
Base Header Level:  3
latex input:        x3-assignment-preamble
latex input:        x3-assignment-mmd-compat
latex input:        x3-assignment-begin
latex footer:       x3-assignment-end


<!--

%\sloppy

\newcommand{\transition}[2]{\textrm{#1} $\rightarrow$ \textrm{#2}}

\newcommand{\fig}[2]{%
  \vspace{\parskip}%
  \begin{center}%
    \includegraphics[#1]{figures/#2}%
  \end{center}%
}

\newcommand{\op}[1]{\operatorname{#1}}

% Vorbereich und Nachbereich
\newcommand{\vb}[1]{\bullet \, #1}
\newcommand{\nb}[1]{#1 \, \bullet}

% aktivierte Transition
\newcommand{\ma}[2]{#1[#2\rangle}
-->


# Eigenschaften von Netzen

## Reversibilität - Lebendigkeit

Unabhängig.

<!--\fig{width=\textwidth}{Reversibel-Lebendig}-->



<!--\newpage-->
## Beschränktheit - Lebendigkeit

Unabhängig.

<!--\fig{width=\textwidth}{Beschraenkt-Lebendig}-->



<!--\newpage-->
## Beschränktheit - Reversibilität

Unabhängig.

<!--\fig{width=\textwidth}{Beschraenkt-Reversibel}-->


<!--\newpage-->
## Stelleninvarianten - Lebendigkeit

Unabhängig.

<!--\fig{width=\textwidth}{P-Invariante-Lebendig}-->



<!--\newpage-->
## Stelleninvarianten - Reversibilität

Unabhängig.

<!--\fig{width=\textwidth}{P-Invariante-Reversibel}-->



## Stelleninvarianten - Beschränktheit

Wenn ein Netz eine Stelleninvariante hat, d.h. <!--$I^T$-->, als homogenes Gleichungssystem gelöst, eine Lösung hat, dann muss das Netz beschränkt sein, denn dann bleibt die nach der Invariante gewichtete Tokensumme immer gleich. Demnach gilt
<!--$\op{Stelleninvariante} \Longleftrightarrow \op{Beschraenktheit}$-->.



<!--\newpage-->
## Transitionsinvarianten - Lebendigkeit

Eine echt positive Transitionsinvariante und Lebendigkeit sind nur unter Einschränkung verknüpft. Nimmt man eine endliches, beschränktes, lebendiges Netz <!--$N$-->, dann muss es für dieses Netz auch eine echt positive Transitionsinvariante geben.

Weitere Zusammenhänge sind nicht erkennbar:

<!--\fig{width=\textwidth}{T-Invariante-Lebendigkeit}-->



<!--\newpage-->
## Transitionsinvarianten - Reversibilität

Transitionsinvarianten beschreiben Zyklen im Erreichbarkeitsgraphen eines Netzes <!--$N = (P,T,W)$-->, allerdings unabhängig von der Startmarkierung <!--$M_0$--> des Netzes. Die Existenz einer echt positiven Transitionsinvariante besagt also, dass eine Markierung <!--$M_0$--> existiert, für die das Netz reversibel ist, also dass es einen endlichen Pfad
<!--$M_0 \xrightarrow{t_1} \ldots \xrightarrow{t_n}M_{n+1}$--> gibt, sodass <!--$M_0 = M_{n+1}$-->.

Eine allgemeine Aussage ist allerdings anhand einer echt positiven Transitionsinvariante nicht treffbar. Es gilt zwar, dass ein reversibles Netz auch eine Transitionsinvariante haben muss, allerdings nicht zwingend eine echt positive.


## Transitionsinvarianten - Beschränktheit

Unabhängig

<!--\fig{width=\textwidth}{T-Invariante-Beschraenkt}-->


<!--\newpage-->
## Transitionsinvarianten - Stelleninvarianten

Die Transitionsinvarianten eines Netzes <!--$N = (P, T, W)$--> sind die Stelleninvarianten des Netzes <!--$N' = (P', T', W')$--> gdw. <!--$W = W'$--> sowie <!--$T' = P$--> und <!--$P' = T$-->.



## Überdeckungsgraph - Lebendigkeit

Es gilt:

<!--$\left( \forall m \in UG : m \xrightarrow{t_1} \ldots \xrightarrow{t_n} m : T \setminus \{t_1, \ldots, t_n\} = \emptyset \right) \Longrightarrow \operatorname{Lebendig}$-->

Die umgekehrte Annahme gilt nicht, denn im UG ist es nicht möglich, von einer <!--$\omega$-->-Markierung wieder zurück zur Ursprungsmarkierung zu gelangen.



## Überdeckungsgraph - Reversibilität

Es gilt:

<!--$\left( \forall m \in UG : m \xrightarrow{t_1} \ldots \xrightarrow{t_n} M_0 \right) \Longrightarrow \operatorname{Reversibel}$-->

Die umgekehrte Annahme gilt aus dem selben Grund wie für "Überdeckungsgraph - Lebendigkeit" nicht.



## Überdeckungsgraph - Stelleninvarianten

Wenn es im Überdeckungsgraph keine Markierungen gibt, welche ein <!--$\omega$--> enthalten, dann muss das dazugehörige Netz beschränkt sein. Da wir außerdem bereits wissen, dass ein beschränktes Netz auch immer eine Stelleninvariante hat, gilt:

<!--$(\forall m \in UG : \forall x \in m : m \neq \omega) \Longleftrightarrow \operatorname{Stelleninvariante}$-->



## Überdecksungsgraph - Beschränktheit

Ein Netz ist genau dann beschränkt, wenn in seinem Überdeckungsgraphen keine <!--$\omega$-->-Stellen vorkommen.



## Überdeckungsgraph - Transitionsinvarianten

Zyklen im Überdeckungsgraphen ohne <!--$\omega \Longrightarrow$--> in Zyklus genutzte
Transitionen haben T-Invariante



## Kondensation des EG und Lebendigkeit

Ein Kondensationsgraph fasst alle stark zusammenhängenden Komponenten zusammen. Dafür müssen die
Komponenten lebendig sein. Alle Teile einer Komponente des KG sind lebendig.

<!--$|KEG| = 1 \Longleftrightarrow Lebendigkeit$-->



## Kondensation des EG und Reversibilität

Besteht der KEG aus einer Komponente, ist das Netz reversibel.

<!--$|KEG| = 1 \Longrightarrow Reversibilitaet$-->



<!--\newpage-->
## Kondensation des EG und Beschränktheit

Es besteht kein Zusammenhang zwischen der Größe des Kondensationsgraphen und der Beschränktheit des Netzes.

<!--\fig{width=\textwidth}{KEG-Beschraenkt}-->



## Kondensation des EG und Stelleninvarianten

Der Kondensationsgraph und positive Stelleninvarianten stehen in keinem
Zusammenhang.

<!--\fig{width=\textwidth}{KEG-S-Invariante}-->



<!--\newpage-->
## Kondensation des EG und Transitionsinvarianten

<!--$\left| KEG \right| = 1 \Longrightarrow$--> echt positive T-Invariante



## Kondensation des EG und Überdeckungsgraph
Der KEG stellt die stark zusammenhängenden Knoten des Überdeckungsgraphen ab.



## Verklemmung und Lebendigkeit

<!--$lebendig \Longrightarrow verklemmungsfrei$
\\ $verklemmt \Longrightarrow \neg lebendig$-->




## Verklemmung und Reversibilität
Ist ein S/T-Netz reversibel, hat es keine Verklemmungen. Da durch die verklemmte
Stelle die Definition der Reversibilität verletzt wäre.

<!--$R \Longrightarrow \neg V$-->



<!--\newpage-->
## Verklemmung und Beschränktheit

Es besteht kein Zusammenhang.

<!--\fig{width=\textwidth}{Verklemmung-Beschraenkt}-->



## Verklemmung und Stelleninvarianten

Ist <!--$M_0$--> verklemmt, ist eine P-Invariante vorhanden, in der alle Stellen mit 1
gewichtet sind.



## Verklemmung und Transitionsinvarianten

Echt positive T-Invariante <!--$\Longrightarrow$--> keine Verklemmung.



## Verklemmung und Überdeckungsgraph

<!--$\neg$--> Senken im ÜG <!--$\Longrightarrow \neg$--> Verklemmung.



## Verklemmung und Kondensation des EG

<!--$|KEG| = 1 \Longrightarrow \neg Verklemmung$-->
