Title:              Theoretische Informatik 1
Subtitle:           Praktikumsaufgabe 3
Author:             Lucas Jenss und Tommy Redel in Gruppe 1
ShortAuthor:        Lucas Jenss und Tommy Redel
UseHelvetica:       yes
Base Header Level:  3
latex input:        x3-assignment-preamble
latex input:        x3-assignment-mmd-compat
latex input:        x3-assignment-begin
latex footer:       x3-assignment-end


<!--

%\sloppy

\newcommand{\transition}[2]{\textrm{#1} $\rightarrow$ \textrm{#2}}

\newcommand{\fig}[2]{%
  \vspace{\parskip}%
  \begin{center}%
    \includegraphics[#1]{figures/#2}%
  \end{center}%
}

\newcommand{\op}[1]{\operatorname{#1}}

% Vorbereich und Nachbereich
\newcommand{\vb}[1]{\bullet \, #1}
\newcommand{\nb}[1]{#1 \, \bullet}

% aktivierte Transition
\newcommand{\ma}[2]{#1[#2\rangle}
-->

# Definitionen

## Lebendigkeit

Eine Transition <!--$t \in T$--> ist lebendig in <!--$N_{M_0}$-->, wenn sie für alle Markierungen <!--$M \in EG$--> M-erreichbar ist.

Ein Netz <!--$N_{M_0}$--> ist lebendig, wenn alle seine Transitionen lebendig sind.



# Eigenschaften von Netzen

## Reversibilität - Lebendigkeit (1)

Unabhängig.

<!--\fig{width=\textwidth}{Reversibel-Lebendig}-->



<!--\newpage-->
## Beschränktheit - Lebendigkeit (2)

Unabhängig.

<!--\fig{width=\textwidth}{Beschraenkt-Lebendig}-->



<!--\newpage-->
## Beschränktheit - Reversibilität (3)

Unabhängig.

<!--\fig{width=\textwidth}{Beschraenkt-Reversibel}-->


<!--\newpage-->
## Stelleninvarianten - Lebendigkeit (4)

Unabhängig.

<!--\fig{width=\textwidth}{P-Invariante-Lebendig}-->



<!--\newpage-->
## Stelleninvarianten - Reversibilität (5)

Unabhängig.

<!--\fig{width=\textwidth}{P-Invariante-Reversibel}-->



<!--\newpage-->
## Stelleninvarianten - Beschränktheit (6)

Wenn ein Netz eine Stelleninvariante hat, d.h. <!--$I^T$-->, als homogenes Gleichungssystem gelöst, eine Lösung hat, dann muss das Netz beschränkt sein, denn dann bleibt die nach der Invariante gewichtete Tokensumme immer gleich. Demnach gilt
<!--$\op{Stelleninvariante} \Longleftrightarrow \op{Beschraenktheit}$-->.



<!--\newpage-->
## Transitionsinvarianten - Lebendigkeit (7)

Eine echt positive Transitionsinvariante und Lebendigkeit sind nur unter Einschränkung verknüpft. Nimmt man eine endliches, beschränktes, lebendiges Netz <!--$N$-->, dann muss es für dieses Netz auch eine echt positive Transitionsinvariante geben.

Weitere Zusammenhänge sind nicht erkennbar:

<!--\fig{width=\textwidth}{T-Invariante-Lebendigkeit}-->



<!--\newpage-->
## Transitionsinvarianten - Reversibilität (8)

Transitionsinvarianten beschreiben Zyklen im Erreichbarkeitsgraphen eines Netzes <!--$N = (P,T,W)$-->, allerdings unabhängig von der Startmarkierung <!--$M_0$--> des Netzes. Die Existenz einer echt positiven Transitionsinvariante besagt also, dass eine Markierung <!--$M_0$--> existiert, für die das Netz reversibel ist, also dass es einen endlichen Pfad
<!--$M_0 \xrightarrow{t_1} \ldots \xrightarrow{t_n}M_{n+1}$--> gibt, sodass <!--$M_0 = M_{n+1}$-->.

Eine allgemeine Aussage ist allerdings anhand einer echt positiven Transitionsinvariante nicht treffbar. Es gilt zwar, dass ein reversibles Netz auch eine Transitionsinvariante haben muss, allerdings nicht zwingend eine echt positive.


<!--\newpage-->
## Transitionsinvarianten - Beschränktheit (9)

Unabhängig

<!--\fig{width=\textwidth}{T-Invariante-Beschraenkt}-->


<!--\newpage-->
## Transitionsinvarianten - Stelleninvarianten (10)

Die Transitionsinvarianten eines Netzes <!--$N = (P, T, W)$--> sind die Stelleninvarianten des Netzes <!--$N' = (P', T', W')$--> gdw. <!--$W = W'$--> sowie <!--$T' = P$--> und <!--$P' = T$-->.


<!--\newpage-->
## Überdeckungsgraph - Lebendigkeit

Es gilt:

<!--$\left( \forall m \in UG : m \xrightarrow{t_1} \ldots \xrightarrow{t_n} m : T \setminus \{t_1, \ldots, t_n\} = \emptyset \right) \Longrightarrow \operatorname{Lebendig}$-->

Die umgekehrte Annahme gilt nicht, denn im UG ist es nicht möglich, von einer <!--$\omega$-->-Markierung wieder zurück zur Ursprungsmarkierung zu gelangen.



<!--\newpage-->
## Überdeckungsgraph - Reversibilität

Es gilt:

<!--$\left( \forall m \in UG : m \xrightarrow{t_1} \ldots \xrightarrow{t_n} M_0 \right) \Longrightarrow \operatorname{Reversibel}$-->

Die umgekehrte Annahme gilt aus dem selben Grund wie für "Überdeckungsgraph - Lebendigkeit" nicht.



<!--\newpage-->
## Überdeckungsgraph - Stelleninvarianten

TODO



<!--\newpage-->
## Überdecksungsgraph - Beschränktheit (13)

Ein Netz ist genau dann beschränkt, wenn in seinem Überdeckungsgraphen keine <!--$\omega$-->-Stellen vorkommen.
