Title:				Theoretische Informatik 1
Subtitle:			Praktikumsaufgabe 2
Author:				Lucas Jenss und Tommy Redel  in Gruppe 1
ShortAuthor:		Lucas Jenss und Tommy Redel
UseHelvetica:		yes
Base Header Level:	3
latex input:		x3-assignment-preamble
latex input:		x3-assignment-mmd-compat
latex input:		x3-assignment-begin
latex footer:		x3-assignment-end


<!--

%\sloppy

\newcommand{\transition}[2]{\textrm{#1} $\rightarrow$ \textrm{#2}}

\newcommand{\fig}[2]{%
  \vspace{\parskip}%
  \begin{center}%
    \includegraphics[#1]{figures/#2}%
  \end{center}%
}

\newcommand{\op}[1]{\operatorname{#1}}

% Vorbereich und Nachbereich
\newcommand{\vb}[1]{\bullet \, #1}
\newcommand{\nb}[1]{#1 \, \bullet}

% aktivierte Transition
\newcommand{\ma}[2]{#1[#2\rangle}
-->


# Teilaufgabe 1

In der ersten Teilaufgabe sollte in Schienennetz mit 8 Gleisabschnitten modelliert werden, welche kreisförmig miteinander verbunden sind.
Für die Gleisabschnitte wurde jeweils eine Stelle modelliert, zwischen denen jeweils eine Transition für die Hin- bzw- Rückrichtung existiert.
Um zu verhindern, dass mehrere Züge einen Gleisabschnitt befahren, wurden wieder Kapazitätsstellen eingefügt.

<!--\fig{width=\textwidth}{teil1}-->

# Teilaufgabe 2

Für die 2. Teilaufgabe wurde das Petrinetz aus Teilaufgabe 1 erweitert. Im linken Teil des Netzes wurde der geforderte Bahnübergang hinzugefügt.
In der Stelle **SchrankenOffen** muss sich nun zusätzlich ein Token befinden, um **t67** oder **t76** schalten zu können.

<!-- \newpage -->
Um das bisherige Modell zu einem 8-förmigen Gleisnetz umzubauen, wurden 4 Weichen hinzugefügt, die es erlauben, vom oberen in den unteren Bereich zu fahren und umgekehrt.
Zwischen den Weichen wurde ein weiterer Gleisabschnitt hinzugefügt.

<!--\fig{width=\textwidth}{teil2}-->

<!--\newpage-->
# Teilaufgabe 3

In der 3. Teilaufgabe sollte das erstellte Netz aus Teilaufgabe 2 näher analysiert werden, um die Korrektheit der Modellierung zu belegen.

## 3a

Dafür wurden zunächst die S-Invarianten mit Hilfe von Charlie berechnet, was zu folgendem Ouput führte.

<!--
\begin{minipage}[t]{0.45\textwidth}
\vspace{1pt}
-->
Deutlich zu erkennen ist hier die konstante Anzahl der Token auf jeder Stelle, sodass durch die S-Invarianten
nachgewiesen wurde, dass keine Züge hinzukommen oder verloren gehen können. Außerdem zeigen die S-Invarianten, dass maximal
ein Zug (Token) auf jeder Stelle (Gleisabschnitt) stehen kann.
<!--
\end{minipage}
\hspace{0.5cm}
\begin{minipage}[t]{0.5\textwidth}%
	\scriptsize%
\begin{lstlisting}[aboveskip=0pt,belowskip=0pt]
minimal semipositive place invariants=
1	|	16.SchrankenGeschlossen		:1,
	|	17.SchrankenOffen			:1
2	|	18.GA9						:1,
	|	23.GAK9						:1
3	|	19.WeicheOben1				:1,
	|	20.WeicheUnten1				:1
4	|	21.WeicheUnten2				:1,
	|	22.WeicheOben2				:1
5	|	24.WeicheOben3				:1,
	|	25.WeicheUnten3				:1
6	|	26.WeicheOben4				:1,
	|	27.WeicheUnten4				:1
7	|	7.GA7						:1,
	|	12.GAK7						:1
8	|	1.GA1						:1,
	|	14.GAK1						:1
9	|	6.GA3						:1,
	|	15.GAK3						:1
10	|	0.GA8						:1,
	|	2.GA2						:1,
	|	3.GA6						:1,
	|	5.GA4						:1,
	|	8.GAK2						:1,
	|	9.GAK4						:1,
	|	11.GAK6						:1,
	|	13.GAK8						:1,
	|	18.GA9						:1
11	|	4.GA5						:1,
	|	10.GAK5						:1
12	|	0.GA8						:1,
	|	1.GA1						:1,
	|	2.GA2						:1,
	|	3.GA6						:1,
	|	4.GA5						:1,
	|	5.GA4						:1,
	|	6.GA3						:1,
	|	7.GA7						:1,
	|	18.GA9						:1
13	|	8.GAK2						:1,
	|	9.GAK4						:1,
	|	10.GAK5						:1,
	|	11.GAK6						:1,
	|	12.GAK7						:1,
	|	13.GAK8						:1,
	|	14.GAK1						:1,
	|	15.GAK3						:1
\end{lstlisting}
\end{minipage}
-->

## 3b
<!--
\begin{minipage}[t]{0.45\textwidth}
\vspace{1pt}
-->
xyz
<!--
\end{minipage}
\hspace{0.5cm}
\begin{minipage}[t]{0.5\textwidth}%
	\scriptsize%
\begin{lstlisting}[aboveskip=0pt,belowskip=0pt]
minimal semipositive transition invariants=
1	|	16.tSOG		:1,
	|	17.tSGO		:1
2	|	26.tWUO1		:1,
	|	27.tWOU1		:1
3	|	28.tWOU2		:1,
	|	29.tWUO2		:1
4	|	30.tWUO3		:1,
	|	31.tWOU3		:1
5	|	32.tWOU4		:1,
	|	33.tWUO4		:1
6	|	2.t18		:1,
	|	3.t81		:1
7	|	4.t21		:1,
	|	5.t12		:1
8	|	10.t45		:1,
	|	11.t54		:1
9	|	12.t56		:1,
	|	13.t65		:1
10	|	6.t32		:1,
	|	7.t23		:1
11	|	8.t34		:1,
	|	9.t43		:1
12	|	0.t78		:1,
	|	1.t87		:1
13	|	14.t67		:1,
	|	15.t76		:1
14	|	24.t92		:1,
	|	25.t29		:1
15	|	19.t94		:1,
	|	21.t49		:1
16	|	0.t78		:1,
	|	3.t81		:1,
	|	5.t12		:1,
	|	7.t23		:1,
	|	8.t34		:1,
	|	10.t45		:1,
	|	12.t56		:1,
	|	14.t67		:1
17	|	1.t87		:1,
	|	2.t18		:1,
	|	4.t21		:1,
	|	6.t32		:1,
	|	9.t43		:1,
	|	11.t54		:1,
	|	13.t65		:1,
	|	15.t76		:1
18	|	22.t89		:1,
	|	23.t98		:1
19	|	18.t96		:1,
	|	20.t69		:1
\end{lstlisting}
\end{minipage}
-->

## 3c

## 3d

* Auf einem Gleisabschnitt ist höchstens ein Zug/Die Anzahl der Züge verändert sich nicht.
	* Durch das Hinzufügen von weiteren Zügen bleiben diese Eigenschaften prinzipiell erhalten, solange man nicht absichtlich
	zwei Züge auf einer Stelle platziert.
* In jeder Situation kann wenigstens ein Zug noch fahren.
	* Würde man auf jede Stelle einen Zug setzen, kann keiner dieser Züge mehr fahren, da es dann kein freies Gleisabschnitt gibt,
	das befahren werden kann.
	* Demnach muss man die maximale Anzahl der Züge beschränken in Abhängigkeit von der Anzahl der Gleisabschnitt, die befahren werden können.
		* 